customization:
  runAsUser: '' # Specific to OCP
image:
  pullSecrets:
    - my-odm-docker-registry
  repository: cp.icr.io/cp/cp4a/odm
decisionCenter:
  sidecar:
    enabled: true
    confSecretRef: users-groups-synchro-secret 
internalDatabase:
  populateSampleData: true
  persistence:
    enabled: false
    useDynamicProvisioning: false
  runAsUser: '' # Specific to OCP
service:
  enableRoute: true # Specific to OCP
license: true
usersPassword: odmAdmin
